/* 부서 */
CREATE TABLE DEPT_EX (
	DEPTNO NUMBER(2) NOT NULL, /* 부서번호 */
	DNAME VARCHAR2(20) NOT NULL, /* 부서명 */
	LOC VARCHAR2(20) NOT NULL /* 위치 */
);

COMMENT ON TABLE DEPT_EX IS '부서';

COMMENT ON COLUMN DEPT_EX.DEPTNO IS '부서번호';

COMMENT ON COLUMN DEPT_EX.DNAME IS '부서명';

COMMENT ON COLUMN DEPT_EX.LOC IS '위치';

CREATE UNIQUE INDEX PK_DEPT_EX
	ON DEPT_EX (
		DEPTNO ASC
	);

ALTER TABLE DEPT_EX
	ADD
		CONSTRAINT PK_DEPT_EX
		PRIMARY KEY (
			DEPTNO
		);

/* 사원정보 */
CREATE TABLE EMP_EX (
	EMPNO NUMBER(5) NOT NULL, /* 사원번호 */
	ENAME VARCHAR2(20) NOT NULL, /* 사원명 */
	JOB VARCHAR2(50) NOT NULL, /* 직업 */
	MGR NUMBER(5) NOT NULL, /* 매니저 */
	HIREDATE DATE NOT NULL, /* 입사일 */
	SAL NUMBER(7,2) NOT NULL, /* 급여 */
	COMM NUMBER(7,2) NOT NULL, /* 성과급 */
	DEPTNO NUMBER(2) /* 부서번호 */
);

COMMENT ON TABLE EMP_EX IS '사원정보';

COMMENT ON COLUMN EMP_EX.EMPNO IS '사원번호';

COMMENT ON COLUMN EMP_EX.ENAME IS '사원명';

COMMENT ON COLUMN EMP_EX.JOB IS '직업';

COMMENT ON COLUMN EMP_EX.MGR IS '매니저';

COMMENT ON COLUMN EMP_EX.HIREDATE IS '입사일';

COMMENT ON COLUMN EMP_EX.SAL IS '급여';

COMMENT ON COLUMN EMP_EX.COMM IS '성과급';

COMMENT ON COLUMN EMP_EX.DEPTNO IS '부서번호';

CREATE UNIQUE INDEX PK_EMP_EX
	ON EMP_EX (
		EMPNO ASC
	);

ALTER TABLE EMP_EX
	ADD
		CONSTRAINT PK_EMP_EX
		PRIMARY KEY (
			EMPNO
		);

ALTER TABLE EMP_EX
	ADD
		CONSTRAINT FK_DEPT_EX_TO_EMP_EX
		FOREIGN KEY (
			DEPTNO
		)
		REFERENCES DEPT_EX (
			DEPTNO
		);